# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: PYTHON_VER
  displayName: 'Python Version'
  type: string
<<<<<<< HEAD
  default: "2.7"
  values:
  - "2.7"
  - "3.6"
- name: ANSIBLE_VER
  displayName: 'Ansible Version'
  type: string
  default: "2.9.0"
  values:
  - "2.9.0"
  - "2.10.0"
=======
  default: python2
  values:
  - python3
  - python4
  - python5
- name: ANSIBLE_VER
  displayName: 'Ansible Version'
  type: string
  default: 9
  values:
  - 9
  - 10
>>>>>>> 6b54757fc54cbf179545d1488a54034ba6e6ab91

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo ${{ parameters.PYTHON_VER }} and ${{ parameters.ANSIBLE_VER }}
  displayName: 'Get predefine parameter'

<<<<<<< HEAD
- script: echo Python${{ parameters.PYTHON_VER }} and ${{ parameters.ANSIBLE_VER }}
  displayName: 'Get predefine parameter'

=======
>>>>>>> 6b54757fc54cbf179545d1488a54034ba6e6ab91
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print('Hello world 1')
      print('Hello world 2')
