# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: PYTHON_VER
  displayName: 'Python Version'
  type: string
  default: python2.7
  values:
  - python3.5
  - python3.6
  - python3.7
- name: ANSIBLE_VER
  displayName: 'Ansible Version'
  type: string
  default: 2.9.0
  values:
  - 2.9.0
  - 2.9.9

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo ${{ parameters.PYTHON_VER }} and ${{ parameters.ANSIBLE_VER }}
  displayName: 'Get predefine parameter'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print('Hello world 1')
      print('Hello world 2')
