parameters:
- name: PYTHON_VER
  displayName: 'Python Version'
  type: string
  default: "3.6"
  values:
    - "2.7"
    - "3.6"
- name: ANSIBLE_VER
  displayName: 'Ansible Version'
  type: string
  default: "devel"
  values:
    - "2.9.0"
    - "devel"

schedules:
- cron: "0 10 0 0 3"
  displayName: 'Execute dev-pipeline every Wednesday' 
  branches:
    - master
  always: true

trigger: none

pool:
  vmImage: 'ubuntu-18.04'

jobs:
  - job: A
    - script: test.py
      displayName: 'Running Tests'

  - job: SendMail
    dependsOn: 
      - A
    condition: failed()
    steps:
      - script: sendmail.py
