schedules:
- cron: "*/3 * * * *"
  displayName: 'Execute dev-pipeline every Wednesday' 
  branches:
    include:
      - master
      - release/*
  always: true
trigger: none

pool:
  vmImage: 'ubuntu-18.04'

jobs:
  - job: A
    steps:
      - bash: echo 'A'
  - job: B
    steps:
      - bash: echo 'B'

- task: EmailReportPPE@1
  inputs:
    sendMailConditionConfig: 'Always'
    subject: '[{environmentStatus}] {passPercentage} tests passed in $(Release.EnvironmentName) stage for $(Build.BuildNumber)'
    defaultDomain: 'microsoft.com'
    groupTestResultsBy: 'run'
    includeCommits: true
    maxTestFailuresToShow: '15'
    includeOthersInTotal: false
    usePreviousEnvironment: false

