parameters:

schedules:
- cron: "0 10 0 0 3"
  displayName: 'Execute dev-pipeline every Wednesday' 
  branches:
    - master
  always: true

trigger: none

pool:
  vmImage: 'ubuntu-18.04'

jobs:
  - job: A
    steps:
      - bash: echo "A"
  - job: B
    steps:
      - bash: echo "B"

