schedules:
- cron: "5 15 * * 1"
  displayName: 'Execute dev-pipeline every Wednesday' 
  branches:
    include:
      - master
      - release/*
  always: true

trigger: none

pool:
  vmImage: 'ubuntu-18.04'

jobs:
  - job: A
    steps:
      - bash: echo 'A'
  - job: B
    steps:
      - bash: echo 'B'

