---
- name: for test
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    subscription_id: f64d4ee8-be94-457d-ba26-3fa6b6506cef
  tasks:
    #- include: main2.yml
    - name: Delete a RegistrationAssignment ---01
      azure_rm_registrationassignment:
        scope: subscriptions//{{ subscription_id }}
        registration_assignment_id:  d96f61e7-af14-440c-be1b-8395c327ae29
        state: absent

    - name: Create a RegistrationAssignment ---check mode
      azure_rm_registrationassignment:
        scope: subscriptions//{{ subscription_id }}
        registration_assignment_id:  d96f61e7-af14-440c-be1b-8395c327ae29
        properties:
          registration_definition_id: /subscriptions/f64d4ee8-be94-457d-ba26-3fa6b6506cef/providers/Microsoft.ManagedServices/registrationDefinitions/d96f61e7-af14-440c-be1b-8395c327ae29
      register: output
      check_mode: yes
    - debug:
        var: output

    - name: Create a RegistrationAssignment ---0101
      azure_rm_registrationassignment:
        scope: subscriptions//{{ subscription_id }}
        #registration_assignment_id:  d96f61e7-af14-440c-be1b-8395c327ae29
        properties:
          registration_definition_id: /subscriptions/f64d4ee8-be94-457d-ba26-3fa6b6506cef/providers/Microsoft.ManagedServices/registrationDefinitions/2e853c04-ad29-4d0b-9f6b-e72c225d96c6
        expand_registration_definition: true
      register: output
      tags: fred
    - debug:
        var: output
      tags: fred

    - name: Create a RegistrationAssignment -- idempotent
      azure_rm_registrationassignment:
        scope: subscriptions//{{ subscription_id }}
        registration_assignment_id:  d96f61e7-af14-440c-be1b-8395c327ae29
        properties:
          registration_definition_id: /subscriptions/f64d4ee8-be94-457d-ba26-3fa6b6506cef/providers/Microsoft.ManagedServices/registrationDefinitions/d96f61e7-af14-440c-be1b-8395c327ae29
        expand_registration_definition: true
      register: output
    - debug:
        var: output

    - name: Create a RegistrationAssignment -- update
      azure_rm_registrationassignment:
        scope: subscriptions//{{ subscription_id }}
        registration_assignment_id:  d96f61e7-af14-440c-be1b-8395c327ae29
        properties:
          registration_definition_id: /subscriptions/f64d4ee8-be94-457d-ba26-3fa6b6506cef/providers/Microsoft.ManagedServices/registrationDefinitions/d96f61e7-af14-440c-be1b-8395c327ae29
        expand_registration_definition: false
      register: output
    - debug:
        var: output


    - name: Get a RegistrationAssignment
      azure_rm_registrationassignment_info:
        scope: subscriptions//{{ subscription_id }}
        registration_assignment_id:  d96f61e7-af14-440c-be1b-8395c327ae29
        expand_registration_definition: true
      register: output
    - debug:
        var: output
